//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace FNWifiLocatorLibrary
{
    public partial class Measure
    {
        public int ID { get; set; }
        public string SSID { get; set; }
        public System.DateTime timestamp { get; set; }
        public short signal { get; set; }
        public short strength { get; set; }
        public string MAC { get; set; }
    }
    
}
