//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace FNWifiLocatorLibrary
{
    public partial class Place
    {
        public Place()
        {
            this.Checkins = new HashSet<Checkin>();
            this.PlacesNetworsValues = new HashSet<PlacesNetworsValue>();
            this.Childs = new HashSet<Place>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string file_in { get; set; }
        public string file_out { get; set; }
        public Nullable<short> m_num { get; set; }
    
        public virtual ICollection<Checkin> Checkins { get; set; }
        public virtual ICollection<PlacesNetworsValue> PlacesNetworsValues { get; set; }
        public virtual ICollection<Place> Childs { get; set; }
        public virtual Place Parent { get; set; }



        public override string ToString()
        {
            return name;
        }
    }
    
}
