//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace FNWifiLocatorLibrary
{
    public partial class PlacesNetworsValue
    {
        public PlacesNetworsValue()
        {
            this.measures = 1;
        }
    
        public int ID { get; set; }
        public short rilevance { get; set; }
        public double media { get; set; }
        public double variance { get; set; }
        public short measures { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Network Network { get; set; }
    }
    
}
