//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace pds1
{
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Places> Places { get; set; }
        public DbSet<Networks> Networks { get; set; }
        public DbSet<Measures> Measures { get; set; }
        public DbSet<PlacesNetworsValues> PlacesNetworsValues { get; set; }
        public DbSet<Checkin> Checkins { get; set; }
    }
}
