//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace pds1
{
    public partial class Network
    {
        public Network()
        {
            this.PlacesNetworsValues = new HashSet<PlacesNetworsValue>();
        }
    
        public int ID { get; set; }
        public string SSID { get; set; }
        public string MAC { get; set; }
        public bool tethering { get; set; }
    
        public virtual ICollection<PlacesNetworsValue> PlacesNetworsValues { get; set; }
    }
    
}
